const struct {
    char *command;
} default_config[] = {
{ "bind    j         = scroll_vert 20"},
{ "bind    k         = scroll_vert -20"},
{ "bind    h         = scroll_horz -20"},
{ "bind    l         = scroll_horz 20"},
{ "bind    <<        = scroll_begin"},
{ "bind    >>        = scroll_end"},
{ "bind    b         = back"},
{ "bind    m         = forward"},
{ "bind    s         = stop "},
{ "bind    r         = reload"},
{ "bind    R         = reload_ign_cache"},
{ "bind    +         = zoom_in"},
{ "bind    -         = zoom_out"},
{ "bind    t         = toggle_status"},
{ "bind    /*        = search %s"},
{ "bind    ?*        = search_reverse %s"},
{ "bind    n         = search"},
{ "bind    N         = search_reverse"},
{ "bind    o _       = uri %s"},
{ "bind    i         = toggle_insert_mode"},
{ "bind    ZZ        = exit"},
{ "set reset_command_mode = 1"},
{ "set status_format = <span background=\"darkblue\" foreground=\"white\"> MODE </span> <span background=\"red\" foreground=\"white\">KEYCMD</span> (LOAD_PROGRESS%)  <b>TITLE</b>  - Uzbl browser"},
{ "set title_format_long = KEYCMD MODE TITLE - Uzbl browser <NAME> > SELECTED_URI"},
{ "set title_format_short = TITLE - Uzbl browser <NAME>"},
{ NULL   }
};
