#!/bin/sh
# this script implements are more useful "browsing experience". 
# We are assuming you want to use the event_manager.py and cookie_daemon.py.
# So, you must have them in the appropriate place, and cookie_daemon_socket must be configured in the default location

# Also, we assume existence of fifo/socket == correctly functioning cookie_daemon/event_manager.
# Checking correct functioning of the daemons here would be too complex here, and it's not implemented in uzbl-core either.
# But this shouldn't cause much problems..


if [ -z "$XDG_DATA_HOME" ]
then
	XDG_DATA_HOME=$HOME/.local/share
fi

if [ -z "$XDG_CACHE_HOME" ]
then
	XDG_CACHE_HOME=$HOME/.cache
fi

if [ ! -S $XDG_CACHE_HOME/uzbl/cookie_daemon_socket ]
then
	$XDG_DATA_HOME/uzbl/scripts/cookie_daemon.py
fi


SOCKET_ID="$RANDOM$RANDOM"
SOCKET_DIR="/tmp"
SOCKET_PATH="$SOCKET_DIR/uzbl_socket_$SOCKET_ID"

uzbl-core "$@" -n $SOCKET_ID &
$XDG_DATA_HOME/uzbl/scripts/event_manager.py -vs $SOCKET_PATH

if [[ -S $SOCKETPATH ]]
then
	rm $SOCKET_PATH
fi
