.Dd $Mdocdate: March 05 2014
.Dt UZBL-EVENT-MANAGER 1
.Os
.Sh NAME
.Nm uzbl-event-manger
.Nd event manager for
.Xr uzbl-core 1
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl vhna
.Op Fl d Ar directories
.Op Fl l Ar plugins
.Op Fl i Ar plugins
.Op Fl p Ar file
.Op Fl s Ar socket
.Ek
.Sh DESCRIPTION
.Nm
is an event manager for
.Xr uzbl-core 1
written in python. An event manager communicates with
.Xr uzbl-core 1
through a text stream and/or a socket. The event manager is supposed to
implement many of the features supported by larger browsers. For
instance, since it receives request from
.Xr uzbl-core 1
it can be used to implement keybindings, browsing history, cookie
management, et cetera.
.Pp
The options are as follows:
.Bl -tag -width "v"
.It Fl v, Fl Fl verbose
Whether to print all messages or just errors.
.It Fl h, Fl Fl help
Whether to print help message and exit afterwards.
.It Fl n, Fl Fl no-daemon
Do not daemonize and run in foreground instead.
.It Fl a, Fl Fl auto-close
Automatically exit after all instances have disconnected.
.It Fl d, Fl Fl plugin-dir Ar directories
Plugin directories in the form of 'dir1:dir2:dir3'.
.It Fl l, Fl Fl load-plugins Ar plugins
Comma separated list of plugins to load.
.It Fl i, Fl Fl ignore-plugins Ar plugins
Comma separated list of plugins to ignore.
.It Fl p, Fl Fl pid-file Ar file
PID file location.
.It Fl s, Fl Fl server-socket Ar socket
Daemon socket location.
.Sh SEE ALSO
.Xr uzbl-core 1
.Sh AUTHORS
.Nm
was written by
.An -nosplit
.An Dieter Plaetinck Aq Mt dieter@plaetinck.be
and
.An Ben Boeckel Aq Mt mathstuf@gmail.com .
