.Dd $Mdocdate: March 05 2014
.Dt UZBL-CORE 1
.Os
.Sh NAME
.Nm uzbl-core
.Nd keyboard controlled browser
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl vhpVe
.Op Fl u Ar uri
.Op Fl n Ar name
.Op Fl c Ar config
.Op Fl g Ar geometry
.Op Fl s Ar socketid
.Op Fl -connect-socket Ar csocket
.Op Fl -display Ar display
.Ek
.Sh DESCRIPTION
.Nm
is the main component of uzbl and is meant for integration with other
tool and scripts. It uses WebKit for rendering and network interaction.
Furthermore, it provides interfaces to get data in and out.
.Pp
It has no built-in means for URL changing, loading/saving of bookmarks,
saving history, et cetera. However, many scripts are provided which use
.Nm
to create a complete browsing experience.
.Pp
The options are as follows:
.Bl -tag -width "XXXXXXXXXXXX"
.It Fl v, Fl -verbose
Whether to print all messages or just errors.
.It Fl h, Fl -help
Wether to print help message and exit afterwards.
.It Fl p, Fl -print-events
Whether to print events to stdout.
.It Fl V, Fl -version
Whether to output the version and quit.
.It Fl u, Fl -uri Ar uri
Uri to load (equivalent to 'uri URI' on load).
.It Fl n, Fl -name Ar name
Name of the current instance (defaults to Xorg window id).
.It Fl c, Fl -config Ar config
Config file to load.
.It Fl g, Fl -geometry Ar geometry
Set the geometry of
.Nm
on start. Accepts either 'maximized' or
alternatively 'WIDTHxHEIGHT+X+Y' as formats.
.It Fl s, Fl -xembed-socket Ar socketid
The Xembed socket ID.
.It Fl -connect-socket Ar csocket
The path to a
.Xr uzbl-event-manager 1
socket.
.It Fl -display Ar display
The X display to use.
.Sh SEE ALSO
.Xr uzbl-event-manager 1
.Sh AUTHORS
.Nm
was written by
.An -nosplit
.An Dieter Plaetinck Aq Mt dieter@plaetinck.be
and
.An Ben Boeckel Aq Mt mathstuf@gmail.com .
