.TH "uzbl" "1" "Fri Jul 5 2013" "" ""
.SH "NAME"
uzbl \- A keyboard controlled browser based on Webkit
.SH "SYNOPSIS"
.B uzbl
[\-u URI] [\-v] [\-n NAME] [\-c CONFIG]
.SH "DESCRIPTION"
.TP 
Very minimal interface. No unnecessary interface elements.
.PP 
Controllable through a FIFO and with external scripts.
.PP 
What is not browsing, is not in uzbl. Things like url changing,
loading/saving of bookmarks, saving history,.. are handled through external
scripts that you write.
.SH "OPTIONS"
.TP 
.I "\-u, \-\-uri=URI"
Uri to load (equivalent to 'set uri = URI')
.TP 
.I "\-v, \-\-verbose"
Whether to print all messages or just errors.
.TP 
.I "\-n, \-\-named=NAME"
Name of the current instance (defaults to Xorg window id)
.TP 
.I "\-c, \-\-config=FILE"
Config file (this is pretty much equivalent to uzbl \-c \- < FILE )
.TP 
.I "\-p, \-\-print-events"
Whether to print events to stdout.
.TP 
.I "\-V, \-\-version"
Output the version and quit.
.TP 
.I "\-\-connect-socket=SOCKET"
The path to an event manager socket. May be specified multiple times.
.TP 
.I "\-s, \-\-socket=SOCKETID"
The Xembed socket ID.
.TP 
.I "\-e, \-\-embed"
Whether uzbl-core should expect to be embedded.
.TP 
.I "\-\-display=DISPLAY"
X display to use
.TP 
.I "\-\-help"
Help
.SH "HOMEPAGE"
The uzbl homepage is http://www.uzbl.org.
.SH "AUTHORS"
Dieter Plaetinck (Dieter@be) <email is dieter AT plaetinck.be>.
.TP 
See /usr/share/doc/uzbl/AUTHORS for all contributers.
