#!/bin/sh

# TODO: Fix up the launcher to check the following paths in order to find the
# correct event_manager.py to run:
#   1. $XDG_DATA_HOME/uzbl/scripts/event_manager.py
# 	2. /usr/local/share/uzbl/examples/data/uzbl/scripts/event_manager.py

if [ -z "$XDG_DATA_HOME" ]
then
	XDG_DATA_HOME=$HOME/.local/share
fi

if [ -z "$XDG_CACHE_HOME" ]
then
	XDG_CACHE_HOME=$HOME/.cache
fi

if [ -f "$XDG_DATA_HOME/uzbl/scripts/event_manager.py" ]
then
	EVENT_MANAGER=$XDG_DATA_HOME/uzbl/scripts/event_manager.py
else
	EVENT_MANAGER=/usr/local/share/uzbl/examples/data/uzbl/scripts/event_manager.py
fi

$EVENT_MANAGER -v "$@"
