#!/bin/sh
#
# This script implements a more useful out-of-the-box "browsing experience".
# It does so by combining uzbl-core with a set of "recommended" tools and
# practices. See docs for more info.
#
# If you want to customize the behavior any of the helper tools, copy them
# to your $XDG_DATA_HOME/uzbl/scripts/ and edit them

PREFIX=/usr/local
if [ -z "$XDG_DATA_HOME" ]
then
	export XDG_DATA_HOME=$HOME/.local/share
fi

if [ -z "$XDG_CACHE_HOME" ]
then
	export XDG_CACHE_HOME=$HOME/.cache
fi

if [ -z "$XDG_CONFIG_HOME" ]
then
	export XDG_CONFIG_HOME=$HOME/.config
fi

# assure the relevant directories exist.
for dir in $XDG_CACHE_HOME/uzbl $XDG_DATA_HOME/uzbl $XDG_CONFIG_HOME/uzbl
do
	if [ ! -d $dir ]
	then
		if ! mkdir -p $dir
		then
			echo "could not create $dir" >&2
			exit 2
		fi
	fi
done

# if no config exists yet in the recommended location, put the default (recommended) config there
if [ ! -f $XDG_CONFIG_HOME/uzbl/config ]
then
	if [ ! -r $PREFIX/share/uzbl/examples/config/config ]
	then
		echo "Error: Global config not found; please check if your distribution ships them separately"
		exit 3
	fi
	if ! cp $PREFIX/share/uzbl/examples/config/config $XDG_CONFIG_HOME/uzbl/config
	then
		echo "Could not copy default config to $XDG_CONFIG_HOME/uzbl/config" >&2
		# Run with the global configs as a last resort
		config="--config $PREFIX/share/uzbl/examples/config/config"
	fi
fi

# uzbl-cookie-manager will exit if another instance is already running
uzbl-cookie-manager

DAEMON_SOCKET=$XDG_CACHE_HOME/uzbl/event_daemon
DAEMON_PID=${DAEMON_SOCKET}.pid

# uzbl-event-manager will exit if one is already running, but you could
# check if the pid file exists here to avoid having to spawn it for a
# slight speedup
#if [ -f "$DAEMON_PID" ]
#then
	uzbl-event-manager -va start
#fi

exec uzbl-core "$@" $config --connect-socket $DAEMON_SOCKET
